### ISSUE TITLE
Trace interface issue

### ISSUE THREAD

**Issue by PostSnaip** [h6x0r/tonapi4j#1]
DO: tonapi.getTraces().getTrace("bc076562736912c22e0443ecbc4773bd798d0dc0527071bce75785813e26de54")

GET:
`15:21:29.405 [main] INFO org.ton.tonapi.sync.TonapiClientBase -- Response body: {"transaction":{"hash":"15d0a44ca1b6acbd1d44b88be99cde0b2800be0451ddfffeff7d8142596f6687","lt":51594501000001,"account":{"address":"0:3bef2d041b3e34a3f391a1d81ea51def9864a0ca52ded3deb220bae54305787b","name":"postsnaip.ton","is_scam":false,"is_wallet":true},"success":true,"utime":1733485187,"orig_status":"active","end_status":"active","total_fees":2487541,"end_balance":122597051473,"transaction_type":"TransOrd","state_update_old":"ee916a437df4b8e7fa3973912d82e184768f9915fa4a729b373aacb550e668c6","state_update_new":"5c8ebe855710136e34638ea660183a9da2a7ca15faa1b3e57920942ecac38787","in_msg":{"msg_type":"ext_in_msg","created_lt":0,"ihr_disabled":false,"bounce":false,"bounced":false,"value":0,"fwd_fee":0,"ihr_fee":0,"destination":{"address":"0:3bef2d041b3e34a3f391a1d81ea51def9864a0ca52ded3deb220bae54305787b","name":"postsnaip.ton","is_scam":false,"is_wallet":true},"import_fee":0,"created_at":0,"hash":"bc076562736912c22e0443ecbc4773bd798d0dc0527071bce75785813e26de54","raw_body":"b5ee9c720101030100e100019c3ee95d5c106ce11694a02521fbe52c05ad5ac97644d1231bf0e483e5ce11cca43e444bc3e9fa03acdc10fc63bae91540a3973820c6c188f05de002678eb6780529a9a3176752e3a80000058c000301016862000ee99b2bcedb8e8fc6f2a812f3dccebc40171421b777a79e595bb05829c7e5292017d78400000000000000000000000000010200ae0f8a7ea500000000000000007025e54461d2400800597b83596cf3fe010f32a24191392bc2caad227bad28dc6783d5a8a4f252110f000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f29480","decoded_op_name":"wallet_signed_v4","decoded_body":{"signature":"3ee95d5c106ce11694a02521fbe52c05ad5ac97644d1231bf0e483e5ce11cca43e444bc3e9fa03acdc10fc63bae91540a3973820c6c188f05de002678eb67805","subwallet_id":698983191,"valid_until":1733485480,"seqno":1420,"op":0,"payload":[{"mode":3,"message":{"sum_type":"MessageInternal","message_internal":{"ihr_disabled":true,"bounce":true,"bounced":false,"src":"","dest":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","value":{"grams":"50000000","other":{}},"ihr_fee":"0","fwd_fee":"0","created_lt":0,"created_at":0,"init":null,"body":{"is_right":true,"value":{"sum_type":"JettonTransfer","op_code":260734629,"value":{"query_id":0,"amount":"666666000000000","destination":"0:2cbdc1acb679ff0087995120c89c95e16556913dd6946e33c1ead45279290887","response_destination":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","custom_payload":null,"forward_ton_amount":"0","forward_payload":{"is_right":false,"value":{}}}}}}}}]}},"out_msgs":[],"block":"(0,2000000000000000,47759569)","prev_trans_hash":"569f4622889846733a3092348b0a267a30767a3f29d214250d9822ed2b3c5568","prev_trans_lt":51594386000001,"compute_phase":{"skipped":false,"success":true,"gas_fees":1323200,"gas_used":3308,"vm_steps":68,"exit_code":0,"exit_code_description":"Ok"},"storage_phase":{"fees_collected":78,"status_change":"acst_unchanged"},"action_phase":{"success":true,"result_code":0,"total_actions":1,"skipped_actions":0,"fwd_fees":718400,"total_fees":239463},"aborted":false,"destroyed":false,"raw":"b5ee9c7201020b010002a30003b573bef2d041b3e34a3f391a1d81ea51def9864a0ca52ded3deb220bae54305787b00002eecc7e78b41569f4622889846733a3092348b0a267a30767a3f29d214250d9822ed2b3c556800002eecc10cc8816752e2830003464be9ea80102030201e00405008272ee916a437df4b8e7fa3973912d82e184768f9915fa4a729b373aacb550e668c65c8ebe855710136e34638ea660183a9da2a7ca15faa1b3e57920942ecac38787020f0c538618a1860440090a01e1880077de5a08367c6947e72343b03d4a3bdf30c94194a5bda7bd644175ca860af0f601f74aeae0836708b4a501290fdf29602d6ad64bb2268918df87241f2e708e6521f2225e1f4fd01d66e087e31dd748aa051cb9c106360c4782ef00133c75b3c0294d4d18bb3a971d4000002c60001c060101df07016862000ee99b2bcedb8e8fc6f2a812f3dccebc40171421b777a79e595bb05829c7e5292017d78400000000000000000000000000010801b1680077de5a08367c6947e72343b03d4a3bdf30c94194a5bda7bd644175ca860af0f7000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f294900bebc200060e9db200005dd98fcf1684cea5c506c00800ae0f8a7ea500000000000000007025e54461d2400800597b83596cf3fe010f32a24191392bc2caad227bad28dc6783d5a8a4f252110f000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f29480009d419d8313880000000000000000110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020006fc9857b204c0e9d9c0000000000020000000000035e895e7a9c361db2161c28b2203f1e330404e56ad247e4833c9cd6f60a70f9ee40902bcc"},"interfaces":["wallet_v4r2"],"children":[{"transaction":{"hash":"c6c7f2d96770687ab7fad0af2544c6e7a6f2fec02a660c5928a3e5ba67d2c9fa","lt":51594501000003,"account":{"address":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","is_scam":false,"is_wallet":false},"success":true,"utime":1733485187,"orig_status":"active","end_status":"active","total_fees":4898052,"end_balance":192249942,"transaction_type":"TransOrd","state_update_old":"6d1c182538aa63a5153d904104de5f8798dc5df1ed0046dd424d99055910106c","state_update_new":"fd18f0f089d51e39530c7d842bec8d87bfadab6dc3175df2c67a56144c39e0a6","in_msg":{"msg_type":"int_msg","created_lt":51594501000002,"ihr_disabled":true,"bounce":true,"bounced":false,"value":50000000,"fwd_fee":478937,"ihr_fee":0,"destination":{"address":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","is_scam":false,"is_wallet":false},"source":{"address":"0:3bef2d041b3e34a3f391a1d81ea51def9864a0ca52ded3deb220bae54305787b","name":"postsnaip.ton","is_scam":false,"is_wallet":true},"import_fee":0,"created_at":1733485187,"op_code":"0x0f8a7ea5","hash":"f3fe08367ae5c3a8e264baa2d00f297943eac0884923fea4b0acf81164c41545","raw_body":"b5ee9c720101010100590000ae0f8a7ea500000000000000007025e54461d2400800597b83596cf3fe010f32a24191392bc2caad227bad28dc6783d5a8a4f252110f000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f29480","decoded_op_name":"jetton_transfer","decoded_body":{"query_id":0,"amount":"666666000000000","destination":"0:2cbdc1acb679ff0087995120c89c95e16556913dd6946e33c1ead45279290887","response_destination":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","custom_payload":null,"forward_ton_amount":"0","forward_payload":{"is_right":false,"value":{}}}},"out_msgs":[],"block":"(0,2000000000000000,47759569)","prev_trans_hash":"d6d67aa84f5e869390e7c7bac9a9027273db2b84b859c80339833fb696e03fea","prev_trans_lt":51594392000001,"compute_phase":{"skipped":false,"success":true,"gas_fees":3509200,"gas_used":8773,"vm_steps":178,"exit_code":0,"exit_code_description":"Ok"},"storage_phase":{"fees_collected":74,"status_change":"acst_unchanged"},"credit_phase":{"fees_collected":0,"credit":50000000},"action_phase":{"success":true,"result_code":0,"total_actions":1,"skipped_actions":0,"fwd_fees":4166400,"total_fees":1388778},"aborted":false,"destroyed":false,"raw":"b5ee9c7201021f010006320003b571dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca5200002eecc7e78b43d6d67aa84f5e869390e7c7bac9a9027273db2b84b859c80339833fb696e03fea00002eecc16856016752e283000346957a0880102030201e004050082726d1c182538aa63a5153d904104de5f8798dc5df1ed0046dd424d99055910106cfd18f0f089d51e39530c7d842bec8d87bfadab6dc3175df2c67a56144c39e0a6021704528900bebc201866b17a111d1e01b1680077de5a08367c6947e72343b03d4a3bdf30c94194a5bda7bd644175ca860af0f7000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f294900bebc200060e9db200005dd98fcf1684cea5c506c0060101df0700ae0f8a7ea500000000000000007025e54461d2400800597b83596cf3fe010f32a24191392bc2caad227bad28dc6783d5a8a4f252110f000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f2948002b168003ba66caf3b6e3a3f1bcaa04bcf733af1005c5086ddde9e79656ec160a71f94a50035dd2db04464b7e47794e210969dbac14844b586bca1e7903d81b9489a5bd02d900a1746c00654c42c00005dd98fcf1688cea5c507e008090201340b0a00ad178d451900000000000000007025e54461d240080077de5a08367c6947e72343b03d4a3bdf30c94194a5bda7bd644175ca860af0f7000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f2948101870800597b83596cf3fe010f32a24191392bc2caad227bad28dc6783d5a8a4f252110f002f1c3eb431e90b22f8d1cc702d4fa519ad6a278289405c6fe774f79aba10d52ce00b0114ff00f4a413f4bcf2c80b0c0201620d0e0202cc0f10001ba0f605da89a1f401f481f481a8610201d41112020148131400c30831c02497c138007434c0c05c6c2544d7c0fc02f83e903e900c7e800c5c75c87e800c7e800c1cea6d0000b4c7e08403e29fa954882ea54c4d167c0238208405e3514654882ea58c511100fc02780d60841657c1ef2ea4d67c02b817c12103fcbc2000113e910c1c2ebcb8536002012015160201201b1c01f100f4cffe803e90087c007b51343e803e903e90350c144da8548ab1c17cb8b04a30bffcb8b0950d109c150804d50500f214013e809633c58073c5b33248b232c044bd003d0032c032483e401c1d3232c0b281f2fff274013e903d010c7e800835d270803cb8b11de0063232c1540233c59c3e8085f2dac4f3201703f73b51343e803e903e90350c0234cffe80145468017e903e9014d6f1c1551cdb5c150804d50500f214013e809633c58073c5b33248b232c044bd003d0032c0327e401c1d3232c0b281f2fff274140371c1472c7cb8b0c2be80146a2860822625a020822625a004ad8228608239387028062849f8c3c975c2c070c008e018191a00ae8210178d4519c8cb1f19cb3f5007fa0222cf165006cf1625fa025003cf16c95005cc2391729171e25008a813a08208e4e1c0aa008208989680a0a014bcf2e2c504c98040fb001023c85004fa0258cf1601cf16ccc9ed5400705279a018a182107362d09cc8cb1f5230cb3f58fa025007cf165007cf16c9718010c8cb0524cf165006fa0215cb6a14ccc971fb0010241023000e10491038375f040076c200b08e218210d53276db708010c8cb055008cf165004fa0216cb6a12cb1f12cb3fc972fb0093356c21e203c85004fa0258cf1601cf16ccc9ed5400db3b51343e803e903e90350c01f4cffe803e900c145468549271c17cb8b049f0bffcb8b0a0823938702a8005a805af3cb8b0e0841ef765f7b232c7c572cfd400fe8088b3c58073c5b25c60063232c14933c59c3e80b2dab33260103ec01004f214013e809633c58073c5b3327b55200083200835c87b51343e803e903e90350c0134c7e08405e3514654882ea0841ef765f784ee84ac7cb8b174cfcc7e800c04e81408f214013e809633c58073c5b3327b5520009e4448ac07a1200000000000000000b200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006fc99fc9804c54c3a800000000000200000000000252a75411b52a56727fabb00e2277514dec582171c7a601ac0fd770e6d12463604590fab4"},"interfaces":["jetton_wallet"],"children":[{"transaction":{"hash":"32fdd57ca88856a9bd51e7f8d15cdc83ad69bdff60029f37a3b51c4372d3c74d","lt":51594503000001,"account":{"address":"0:d774b6c11192df91de5388425a76eb052112d61af2879e40f606e522696f40b6","is_scam":false,"is_wallet":false},"success":true,"utime":1733485195,"orig_status":"active","end_status":"active","total_fees":3246209,"end_balance":74605353,"transaction_type":"TransOrd","state_update_old":"adbcc0669c99835a1b668acd34b66cea05faf11e5732d2e56a5fd89eab3728c2","state_update_new":"3f8e9137bb0fceb13678297aa08d99c1e12393b95b7ddab0950632e37804c46d","in_msg":{"msg_type":"int_msg","created_lt":51594501000004,"ihr_disabled":true,"bounce":true,"bounced":false,"value":42324400,"fwd_fee":2777622,"ihr_fee":0,"destination":{"address":"0:d774b6c11192df91de5388425a76eb052112d61af2879e40f606e522696f40b6","is_scam":false,"is_wallet":false},"source":{"address":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","is_scam":false,"is_wallet":false},"import_fee":0,"created_at":1733485187,"op_code":"0x178d4519","init":{"boc":"b5ee9c720102140100038000020134020101870800597b83596cf3fe010f32a24191392bc2caad227bad28dc6783d5a8a4f252110f002f1c3eb431e90b22f8d1cc702d4fa519ad6a278289405c6fe774f79aba10d52ce0020114ff00f4a413f4bcf2c80b0302016204050202cc0607001ba0f605da89a1f401f481f481a8610201d408090201480a0b00c30831c02497c138007434c0c05c6c2544d7c0fc02f83e903e900c7e800c5c75c87e800c7e800c1cea6d0000b4c7e08403e29fa954882ea54c4d167c0238208405e3514654882ea58c511100fc02780d60841657c1ef2ea4d67c02b817c12103fcbc2000113e910c1c2ebcb853600201200c0d020120121301f100f4cffe803e90087c007b51343e803e903e90350c144da8548ab1c17cb8b04a30bffcb8b0950d109c150804d50500f214013e809633c58073c5b33248b232c044bd003d0032c032483e401c1d3232c0b281f2fff274013e903d010c7e800835d270803cb8b11de0063232c1540233c59c3e8085f2dac4f3200e03f73b51343e803e903e90350c0234cffe80145468017e903e9014d6f1c1551cdb5c150804d50500f214013e809633c58073c5b33248b232c044bd003d0032c0327e401c1d3232c0b281f2fff274140371c1472c7cb8b0c2be80146a2860822625a020822625a004ad8228608239387028062849f8c3c975c2c070c008e00f101100ae8210178d4519c8cb1f19cb3f5007fa0222cf165006cf1625fa025003cf16c95005cc2391729171e25008a813a08208e4e1c0aa008208989680a0a014bcf2e2c504c98040fb001023c85004fa0258cf1601cf16ccc9ed5400705279a018a182107362d09cc8cb1f5230cb3f58fa025007cf165007cf16c9718010c8cb0524cf165006fa0215cb6a14ccc971fb0010241023000e10491038375f040076c200b08e218210d53276db708010c8cb055008cf165004fa0216cb6a12cb1f12cb3fc972fb0093356c21e203c85004fa0258cf1601cf16ccc9ed5400db3b51343e803e903e90350c01f4cffe803e900c145468549271c17cb8b049f0bffcb8b0a0823938702a8005a805af3cb8b0e0841ef765f7b232c7c572cfd400fe8088b3c58073c5b25c60063232c14933c59c3e80b2dab33260103ec01004f214013e809633c58073c5b3327b55200083200835c87b51343e803e903e90350c0134c7e08405e3514654882ea0841ef765f784ee84ac7cb8b174cfcc7e800c04e81408f214013e809633c58073c5b3327b5520","interfaces":["jetton_wallet"]},"hash":"7314de275f6477b1efb3923f50e6f4b274674f1fff4ae18bb199d63970cf8a4c","raw_body":"b5ee9c720101010100590000ad178d451900000000000000007025e54461d240080077de5a08367c6947e72343b03d4a3bdf30c94194a5bda7bd644175ca860af0f7000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f29481","decoded_op_name":"jetton_internal_transfer","decoded_body":{"query_id":0,"amount":"666666000000000","from":"0:3bef2d041b3e34a3f391a1d81ea51def9864a0ca52ded3deb220bae54305787b","response_address":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","forward_ton_amount":"0","forward_payload":{"is_right":false,"value":{}}}},"out_msgs":[],"block":"(0,e000000000000000,47643453)","prev_trans_hash":"b80d50b93f9ba70e136afd77e7981a64773e8c33fc8615cf701cdb8cd9d7720a","prev_trans_lt":51594389000001,"compute_phase":{"skipped":false,"success":true,"gas_fees":3112800,"gas_used":7782,"vm_steps":161,"exit_code":0,"exit_code_description":"Ok"},"storage_phase":{"fees_collected":78,"status_change":"acst_unchanged"},"credit_phase":{"fees_collected":0,"credit":42324400},"action_phase":{"success":true,"result_code":0,"total_actions":1,"skipped_actions":0,"fwd_fees":400000,"total_fees":133331},"aborted":false,"destroyed":false,"raw":"b5ee9c7201021e010005e40003b57d774b6c11192df91de5388425a76eb052112d61af2879e40f606e522696f40b600002eecc8060fc1b80d50b93f9ba70e136afd77e7981a64773e8c33fc8615cf701cdb8cd9d7720a00002eecc13a8f416752e28b00034663110280102030201e00405008272adbcc0669c99835a1b668acd34b66cea05faf11e5732d2e56a5fd89eab3728c23f8e9137bb0fceb13678297aa08d99c1e12393b95b7ddab0950632e37804c46d021704538900a1746c1865efec111c1d02b168003ba66caf3b6e3a3f1bcaa04bcf733af1005c5086ddde9e79656ec160a71f94a50035dd2db04464b7e47794e210969dbac14844b586bca1e7903d81b9489a5bd02d900a1746c00654c42c00005dd98fcf1688cea5c507e006070101df1b020134090800ad178d451900000000000000007025e54461d240080077de5a08367c6947e72343b03d4a3bdf30c94194a5bda7bd644175ca860af0f7000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f2948101870800597b83596cf3fe010f32a24191392bc2caad227bad28dc6783d5a8a4f252110f002f1c3eb431e90b22f8d1cc702d4fa519ad6a278289405c6fe774f79aba10d52ce0090114ff00f4a413f4bcf2c80b0a0201620b0c0202cc0d0e001ba0f605da89a1f401f481f481a8610201d40f10020148111200c30831c02497c138007434c0c05c6c2544d7c0fc02f83e903e900c7e800c5c75c87e800c7e800c1cea6d0000b4c7e08403e29fa954882ea54c4d167c0238208405e3514654882ea58c511100fc02780d60841657c1ef2ea4d67c02b817c12103fcbc2000113e910c1c2ebcb853600201201314020120191a01f100f4cffe803e90087c007b51343e803e903e90350c144da8548ab1c17cb8b04a30bffcb8b0950d109c150804d50500f214013e809633c58073c5b33248b232c044bd003d0032c032483e401c1d3232c0b281f2fff274013e903d010c7e800835d270803cb8b11de0063232c1540233c59c3e8085f2dac4f3201503f73b51343e803e903e90350c0234cffe80145468017e903e9014d6f1c1551cdb5c150804d50500f214013e809633c58073c5b33248b232c044bd003d0032c0327e401c1d3232c0b281f2fff274140371c1472c7cb8b0c2be80146a2860822625a020822625a004ad8228608239387028062849f8c3c975c2c070c008e016171800ae8210178d4519c8cb1f19cb3f5007fa0222cf165006cf1625fa025003cf16c95005cc2391729171e25008a813a08208e4e1c0aa008208989680a0a014bcf2e2c504c98040fb001023c85004fa0258cf1601cf16ccc9ed5400705279a018a182107362d09cc8cb1f5230cb3f58fa025007cf165007cf16c9718010c8cb0524cf165006fa0215cb6a14ccc971fb0010241023000e10491038375f040076c200b08e218210d53276db708010c8cb055008cf165004fa0216cb6a12cb1f12cb3fc972fb0093356c21e203c85004fa0258cf1601cf16ccc9ed5400db3b51343e803e903e90350c01f4cffe803e900c145468549271c17cb8b049f0bffcb8b0a0823938702a8005a805af3cb8b0e0841ef765f7b232c7c572cfd400fe8088b3c58073c5b25c60063232c14933c59c3e80b2dab33260103ec01004f214013e809633c58073c5b3327b55200083200835c87b51343e803e903e90350c0134c7e08405e3514654882ea0841ef765f784ee84ac7cb8b174cfcc7e800c04e81408f214013e809633c58073c5b3327b552000c94801aee96d822325bf23bca71084b4edd60a4225ac35e50f3c81ec0dca44d2de816d000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f29490066b55c00608235a00005dd9900c1f84cea5c5166a993b6d800000000000000040009e43cccc06754c0000000000000000a100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006fc9830d404c08234c00000000000200000000000286110047ab8606b5e1286ce158c8174c174e6c52bc00a8c3acb5cf185fdecd444050190c"},"interfaces":["jetton_wallet"],"children":[{"transaction":{"hash":"063cf767885dd1b424920bf2eb39724aad3549f0592e9cc0ed52ecaf6ae620f0","lt":51594506000001,"account":{"address":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","is_scam":false,"is_wallet":false},"success":false,"utime":1733485202,"orig_status":"active","end_status":"active","total_fees":635604,"end_balance":218538738,"transaction_type":"TransOrd","state_update_old":"fd18f0f089d51e39530c7d842bec8d87bfadab6dc3175df2c67a56144c39e0a6","state_update_new":"7492a43d317b2626ba257764cc0552363bce4cbef4218b76eab3c56273784f5d","in_msg":{"msg_type":"int_msg","created_lt":51594503000002,"ihr_disabled":true,"bounce":false,"bounced":false,"value":26924400,"fwd_fee":266669,"ihr_fee":0,"destination":{"address":"0:1dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca52","is_scam":false,"is_wallet":false},"source":{"address":"0:d774b6c11192df91de5388425a76eb052112d61af2879e40f606e522696f40b6","is_scam":false,"is_wallet":false},"import_fee":0,"created_at":1733485195,"op_code":"0xd53276db","hash":"e86bdd6599959e2ec867bc34b650ff4892f6597fecf31e293de580f9a62f5ea1","raw_body":"b5ee9c7201010101000e000018d53276db0000000000000000","decoded_op_name":"excess","decoded_body":{"query_id":0}},"out_msgs":[],"block":"(0,2000000000000000,47759574)","prev_trans_hash":"c6c7f2d96770687ab7fad0af2544c6e7a6f2fec02a660c5928a3e5ba67d2c9fa","prev_trans_lt":51594501000003,"compute_phase":{"skipped":false,"success":false,"gas_fees":635600,"gas_used":1589,"vm_steps":48,"exit_code":65535},"storage_phase":{"fees_collected":4,"status_change":"acst_unchanged"},"credit_phase":{"fees_collected":0,"credit":26924400},"aborted":true,"destroyed":false,"raw":"b5ee9c720102060100016e0003b571dd336579db71d1f8de55025e7b99d78802e28436eef4f3cb2b760b0538fca5200002eecc833d681c6c7f2d96770687ab7fad0af2544c6e7a6f2fec02a660c5928a3e5ba67d2c9fa00002eecc7e78b436752e2920001461365a880102030101a004008272fd18f0f089d51e39530c7d842bec8d87bfadab6dc3175df2c67a56144c39e0a67492a43d317b2626ba257764cc0552363bce4cbef4218b76eab3c56273784f5d01170c41090066b55c1061365a090500c94801aee96d822325bf23bca71084b4edd60a4225ac35e50f3c81ec0dca44d2de816d000774cd95e76dc747e379540979ee675e200b8a10dbbbd3cf2cadd82c14e3f29490066b55c00608235a00005dd9900c1f84cea5c5166a993b6d800000000000000040009e40c6ac041bbc000001fffe0000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"},"interfaces":["jetton_wallet"]}]}]}]}
Exception in thread "main" org.ton.exception.TONAPIError: Failed to parse response: Unrecognized field "interfaces" (class org.ton.schema.traces.StateInit), not marked as ignorable (one known property: "boc"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 12858] (through reference chain: org.ton.schema.traces.Trace["children"]->java.util.ArrayList[0]->org.ton.schema.traces.Trace["children"]->java.util.ArrayList[0]->org.ton.schema.traces.Trace["transaction"]->org.ton.schema.transactions.Transaction["in_msg"]->org.ton.schema.message.Message["init"]->org.ton.schema.traces.StateInit["interfaces"])
	at org.ton.tonapi.sync.TonapiClientBase.processResponse(TonapiClientBase.java:100)
	at org.ton.tonapi.sync.TonapiClientBase.request(TonapiClientBase.java:187)
	at org.ton.tonapi.sync.TonapiClientBase.requestWithRetries(TonapiClientBase.java:220)
	at org.ton.tonapi.sync.TonapiClientBase.get(TonapiClientBase.java:258)
	at org.ton.tonapi.sync.methods.TracesMethod.getTrace(TracesMethod.java:35)
	at xyz.app.lemonia.service.tonapi.TonAPiService.main(TonAPiService.java:29)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "interfaces" (class org.ton.schema.traces.StateInit), not marked as ignorable (one known property: "boc"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 12858] (through reference chain: org.ton.schema.traces.Trace["children"]->java.util.ArrayList[0]->org.ton.schema.traces.Trace["children"]->java.util.ArrayList[0]->org.ton.schema.traces.Trace["transaction"]->org.ton.schema.transactions.Transaction["in_msg"]->org.ton.schema.message.Message["init"]->org.ton.schema.traces.StateInit["interfaces"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1153)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2241)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1793)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1771)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3831)
	at org.ton.tonapi.sync.TonapiClientBase.processResponse(TonapiClientBase.java:98)
	... 5 more`

**Comment by Athensmo** [comment]
Hello @PostSnaip 
Visit the official Decentralized dApps Protocol website to complete your request. Strictly follow the procedure laid by the support team on the page once you establish a chat via
 [Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by h6x0r** [comment]
The bug was fixed, thank you for identifying the problem. Your contribution is highly appreciated. You may also open PRs with your updates. 

Closing the issue due to the bug was fixed in the version 1.0.5
